apiVersion: v1
kind: Service
metadata:
 name:Webservices-Java-svc
spec:
 type: NodePort
 selector:
   app:Webservices-Java
   env: prod
 ports:
 - nodePort: 32415
   protocol: TCP
   port: 80
   targetPort: 80
